[package]
name = "logic-of-events"
version = "0.1.0"
authors = ["Henrik Jürges <juerges.henrik@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[[bin]]
name = "loe"
path = "src/main.rs"